const allTypes = {
  GET_CARETAKERS: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST',
  Success_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_SUCCESS',
  Failed_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_FAILED',

  SAVE_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_DETAILS',
  SUCCESS_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_SUCCESS',
  FAILED_PROFILE: 'SEND_REQUEST_TO_SAVE_PROFILE_FAILED',

  GET_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST',
  SUCCES_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST_SUCCESS',
  FAILED_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST_FAILED',

  ACCEPT_PATIENT_REQUEST: 'SEND_REQUEST_TO_ACCEPT_PATIENT_REQUEST',
  SUCCES_ACCEPT_PATIENT_REQUEST:
    'SEND_REQUEST_TO_ACCEPT_PATIENT_REQUEST_SUCCESS',
  FAILED_ACCEPT_PATIENT_REQUEST:
    'SEND_REQUEST_TO_ACCEPT_PATIENT_REQUEST_FAILED',

  DELETE_PATIENT_REQUEST: 'SEND_REQUEST_TO_DELETE_PATIENT_REQUEST',
  SUCCES_DELETE_PATIENT_REQUEST:
    'SEND_REQUEST_TO_DELETE_PATIENT_REQUEST_SUCCESS',
  FAILED_DELETE_PATIENT_REQUEST:
    'SEND_REQUEST_TO_DELETE_PATIENT_REQUEST_FAILED',

  GET_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS',
  SUCCES_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_SUCCESS',
  FAILED_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_FAILED',

  NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT',
  SUCCESS_NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT_SUCCESS',
  FAILED_NOTIFY_PATIENT: 'SEND_REQUEST_TO_NOTIFY_PATIENT_FAILED',

  GET_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES',
  SUCCESS_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES_SUCCESS',
  FAILED_MED_IMAGES: 'SEND_REQUEST_TO_GET_MED_IMAGES_FAILED',

  SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL',
  SUCCESS_SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL_SUCSESS',
  FAILED_SEND_EMAIL: 'SEND_REQUEST_TO_SEND_EMAIL_FAILED',

  SEND_CARETAKER_REQUEST: 'SEND_REQUEST_TO SEND_CARETAKER_REQUEST',
  SUCCESS_CARETAKER_REQUEST: 'SEND_REQUEST_TO_SEND_CARETAKER_REQUEST_SUCCESS',
  FAILED_CARETAKER_REQUEST: 'SEND_REQUEST_TO_SEND_CARETAKER_REQUEST_FAILED',

  SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES',
  SUCCESS_SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES_SUCCESS',
  FAILED_SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES_FAILED',

  SYNC_MEDS: 'SEND_REQUEST_TO_SYNC_MEDS',
  SUCCESS_SYNC_MEDS: 'SEND_REQUEST_TO_SYNC_MEDS_SUCCESS',
  FAILED_SYNC_MEDS: 'SEND_REQUEST_TO_SYNC_MEDS_FAILED',

  SYNC_HISTORY: 'SEND_REQUEST_TO_SYNC_HISTORY',
  SUCCESS_SYNC_HISTORY: 'SEND_REQUEST_TO_SYNC_HISTORY_SUCCESS',
  FAILED_SYNC_HISTORY: 'SEND_REQUEST_TO_SYNC_HISTORY_FAILED',

  GET_MED_HISTORY: 'SEND_REQUEST_TO_GET_MED_HISTORY',
  GET_MED_HISTORY_SUCCESS: 'SEND_REQUEST_TO_GET_MED_HISTORY_SUCCESS',
  GET_MED_HISTORY_FAILED: 'SEND_REQUEST_TO_GET_MED_HISTORY_FAILED',

  GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES',
  SUCCES_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_SUCCESS',
  FAILED_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_FAILED',

  GET_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT',
  SUCCES_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_SUCCESS',
  FAILED_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_FAILED',

  PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF',
  SUCCESS_PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF_SUCCESS',
  FAILED_PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF_FAILED',

  LOGIN_REQUEST: 'SEND_REQUEST_TO_LOGIN',
  SUCCESS_LOGIN: 'SEND_REQUEST_LOGIN_SUCCESS',
  FAILED_LOGIN: 'SEND_REQUEST_LOGIN_FAILED',

  SIGNUP_REQUEST: 'SEND_REQUEST_TO_SIGNUP',
  SUCCESS_SIGNUP: 'SEND_REQUEST_SIGNUP_SUCCESS',
  FAILED_SIGNUP: 'SEND_REQUEST_SIGNUP_FAILED',
};

export default allTypes;
