const Types = {
  GET_CARETAKERS: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST',
  Success_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_SUCCESS',
  Failed_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_FAILED',
  
  PUT_PROFILE: 'SEND_REQUEST_TO_PUT_PROFILE',
  SUCCES_PROFILE: 'SEND_REQUEST_TO_PUT_PROFILE_SUCCESS',
  FAILED_PROFILE: 'SEND_REQUEST_TO_PUT_PROFILE_FAILED',

  GET_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT',
  SUCCES_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_SUCCESS',
  FAILED_PATIENT: 'SEND_REQUEST_TO_GET_PATIENT_FAILED',

  GET_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST',
  SUCCES_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST_SUCCESS',
  FAILED_PATIENT_REQUEST: 'SEND_REQUEST_TO_GET_PATIENT_REQUEST_FAILED',

  GET_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS',
  SUCCES_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_SUCCESS',
  FAILED_PATIENT_DETAILS: 'SEND_REQUEST_TO_GET_PATIENT_DETAILS_FAILED',

  GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES',
  SUCCES_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_SUCCESS',
  FAILED_GET_IMAGES: 'SEND_REQUEST_TO_GET_IMAGES_FAILED',

  SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES',
  SUCCES_SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES_SUCCESS',
  FAILED_SEND_IMAGES: 'SEND_REQUEST_TO_SEND_IMAGES_FAILED',

  PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF',
  SUCCESS_PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF_SUCCESS',
  FAILED_PDF_DOWNLOAD: 'SEND_REQUEST_TO_DOWNLOAD_PDF_FAILED',

  LOGIN_REQUest: 'SEND_REQUEST_TO_LOGIN',
  SUCCESS_LOGIN: 'SEND_REQUEST_LOGIN_SUCCESS',
  FAILED_LOGIN: 'SEND_REQUEST_LOGIN_FAILED',

};

export default Types;
