const Types = {
  GET_CARETAKERS: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST',
  Success_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_SUCCESS',
  Failed_CareTAKER_REQUEST: 'SEND_REQUEST_TO_GET_CARETAKERS_REQUEST_FAILED',
};

export default Types;
